# Generated by Django 6.0.1 on 2026-01-28 20:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("qbank", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="questioninteraction",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="subtopic",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="subtopics",
                to="qbank.subject",
            ),
        ),
        migrations.AddField(
            model_name="chapter",
            name="sub_topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="chapters",
                to="qbank.subtopic",
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="chapter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="qbank.chapter"
            ),
        ),
        migrations.AddField(
            model_name="userprogress",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AlterUniqueTogether(
            name="questioninteraction",
            unique_together={("user", "question")},
        ),
        migrations.AlterUniqueTogether(
            name="userprogress",
            unique_together={("user", "chapter")},
        ),
    ]
